# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'a Lodjinha' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for a Lodjinha  
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireObjectMapper', '~> 5.0'
  pod 'AlamofireImage', '~> 3.3'
  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'


  target 'a LodjinhaTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '~> 4.0'
    pod 'RxTest',     '~> 4.0'
  end

  target 'a LodjinhaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
